server:
  port: 18080
spring:
  application:
    name: wrdb
  r2dbc:
    name: wrdb
    url: r2dbcs:mysql://localhost:3306/wrdb?serverTimezone=GMT%2B8
    username: wrdb
    password: wrdb
    pool:
      enabled: true
      validation-query: select 1

