server:
  port: 18080
spring:
  devtools:
    add-properties: true
  application:
    name: wrdb
  r2dbc:
    name: bookkeeping
    url: r2dbcs:mysql://121.4.124.247:55001/bookkeeping?serverTimezone=GMT%2B8
    username: bookkeeping
    password: wE5GR4KmkrcKnLMF
    pool:
      enabled: true
      validation-query: select 1
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
