server:
  port: 18080
spring:
  application:
    name: bookkeeping-backend
  r2dbc:
    name: bookkeeping
    url: r2dbcs:mysql://121.4.124.247:55001/bookkeeping?serverTimezone=GMT%2B8
    username: bookkeeping
    password: wE5GR4KmkrcKnLMF
    pool:
      enabled: true
      validation-query: select 1
